### ISSUE TITLE
Add test with Src Generator for System.Text.Json

### ISSUE THREAD

**Issue by dylanvdmerwe** [Im5tu/SerializationBenchmarks#2]
It would be very interesting to include a test in this suite that includes the [JsonSerializable] source generator from Microsoft for the System.Text.Json serializer and deserializer.

**Comment by Im5tu** [comment]
Nice idea! I'll get around to doing this later in Jan when the new year rush is over unless you or someone else wants to contribute it? If so, please just add a different test case so that we can differ between the src gen and non-src gen'd one (:

**Comment by Im5tu** [comment]
Implemented, will release the results in the 24-48 hours or so! :)
